name: quantlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21
  - matplotlib>=3.5
  - scipy>=1.7
  - ipywidgets>=8.0
  - ipympl
  - jupyterlab
  - ipykernel
  - nodejs  # Required to activate widget extensions
  - pandas
  - openpyxl
  - pip:
    - nest-asyncio  # Helps fix event loop issues in Jupyter
    - torch
    - scikit-learn
    - py_vollib
    - numba
    - QuantLib
    - statsmodels


#  - tqdm

# Set environment variables
variables:
  KMP_DUPLICATE_LIB_OK: TRUE

